In [33]:
import pandas as pd
import numpy as np

In [2]:
session_ids = ['Y2026R01S1', 'Y2026R01S2', 'Y2026R01S3', 'Y2026R01S4', 'Y2026R01S5']

In [3]:
data_laps = pd.read_parquet('../data/gold/session_laps_Y2026.parquet')
data_laps = data_laps[data_laps['session_id'].isin(session_ids)]
data_laps['session_id'].value_counts().sort_index()

session_id
Y2026R01S1    487
Y2026R01S2    544
Y2026R01S3    377
Y2026R01S4    353
Name: count, dtype: int64

In [4]:
data_track_status = pd.read_parquet('../data/gold/session_track_status_Y2026.parquet')
data_track_status = data_track_status[data_track_status['session_id'].isin(session_ids)]
data_track_status['session_id'].value_counts().sort_index()

session_id
Y2026R01S1    15
Y2026R01S2     8
Y2026R01S3    15
Y2026R01S4    15
Name: count, dtype: int64

In [5]:
data_laps[['driver_name', 'timestamp_lap_start', 'time_lap', 'is_accurate']].sort_values(by=['timestamp_lap_start'])

     driver_name              timestamp_lap_start  time_lap  is_accurate
206          HUL 2026-03-06 01:30:02.994000+00:00       NaN        False
255          OCO 2026-03-06 01:30:08.459000+00:00       NaN        False
462          BEA 2026-03-06 01:30:16.718000+00:00       NaN        False
331          HAM 2026-03-06 01:30:22.984000+00:00   121.722        False
122          ANT 2026-03-06 01:30:23.689000+00:00       NaN        False
...          ...                              ...       ...          ...
1687         HAM 2026-03-07 06:18:46.275000+00:00    79.478         True
1645         LIN 2026-03-07 06:18:59.323000+00:00    81.247         True
1709         RUS 2026-03-07 06:19:01.547000+00:00       NaN        False
1603         LAW 2026-03-07 06:19:09.930000+00:00    79.994         True
1467         HAD 2026-03-07 06:19:48.721000+00:00       NaN        False

[1761 rows x 4 columns]

In [6]:
data_laps[['is_fastf1_generated', 'is_accurate']].value_counts()

is_fastf1_generated  is_accurate
False                True           993
                     False          768
Name: count, dtype: int64

In [7]:
data_laps.query('is_accurate')\
    [['driver_name', 'timestamp_lap_start', 'time_lap', 'is_accurate']].sort_values(by=['timestamp_lap_start'])

     driver_name              timestamp_lap_start  time_lap  is_accurate
442          PIA 2026-03-06 01:34:59.881000+00:00    94.777         True
148          LEC 2026-03-06 01:35:02.165000+00:00    91.362         True
184          ALB 2026-03-06 01:35:20.418000+00:00   124.080         True
307          COL 2026-03-06 01:35:28.600000+00:00    87.466         True
393          RUS 2026-03-06 01:35:38.124000+00:00    86.483         True
...          ...                              ...       ...          ...
1466         HAD 2026-03-07 06:18:29.418000+00:00    79.303         True
1432         NOR 2026-03-07 06:18:39.322000+00:00    79.475         True
1687         HAM 2026-03-07 06:18:46.275000+00:00    79.478         True
1645         LIN 2026-03-07 06:18:59.323000+00:00    81.247         True
1603         LAW 2026-03-07 06:19:09.930000+00:00    79.994         True

[993 rows x 4 columns]

In [8]:
import sys
sys.path.append('..')
import src.visualization_app.plotly_time_sync as plot_module

In [9]:
data_laps.sort_values(by=['time_lap'])

,year,session_id,driver_number,driver_name,driver_team,lap_number,stint,timestamp_lap_start,timing_start_lap,timing_end_lap,...,speed_i2,speed_fl,speed_st,is_personal_best,track_status,position,deleted_status,deleted_reason,is_accurate,is_fastf1_generated
1708,2026,Y2026R01S4,63,RUS,Mercedes,21,8.0,2026-03-07 06:17:43.029000+00:00,5424.317,5502.835,...,284.0,296.0,296.0,True,1.0,None,True,None,True,False
1509,2026,Y2026R01S4,12,ANT,Mercedes,17,6.0,2026-03-07 06:17:11.266000+00:00,5392.554,5471.365,...,274.0,298.0,289.0,True,1.0,None,True,None,True,False
1697,2026,Y2026R01S4,63,RUS,Mercedes,10,4.0,2026-03-07 05:37:49.295000+00:00,3030.583,3109.517,...,285.0,301.0,294.0,True,1.0,None,True,None,True,False
1700,2026,Y2026R01S4,63,RUS,Mercedes,13,5.0,2026-03-07 05:45:06.700000+00:00,3467.988,3546.975,...,280.0,297.0,294.0,False,1.0,None,True,None,True,False
1357,2026,Y2026R01S3,63,RUS,Mercedes,20,5.0,2026-03-07 02:47:50.126000+00:00,5030.064,5109.117,...,292.0,307.0,294.0,True,1.0,None,True,None,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743,2026,Y2026R01S4,87,BEA,Haas F1 Team,1,1.0,2026-03-07 05:00:16.118000+00:00,777.406,890.622,...,262.0,271.0,65.0,False,1.0,None,True,None,False,False
1747,2026,Y2026R01S4,87,BEA,Haas F1 Team,5,1.0,2026-03-07 05:06:44.218000+00:00,1165.506,1941.468,...,282.0,NaN,300.0,False,125.0,None,True,None,False,False
1752,2026,Y2026R01S4,87,BEA,Haas F1 Team,10,2.0,2026-03-07 05:26:06.503000+00:00,2327.791,2812.744,...,230.0,NaN,238.0,False,12.0,None,True,None,False,False
1756,2026,Y2026R01S4,87,BEA,Haas F1 Team,14,3.0,2026-03-07 05:39:01.524000+00:00,3102.812,3386.408,...,278.0,NaN,201.0,False,1.0,None,True,None,False,False
1760,2026,Y2026R01S4,87,BEA,Haas F1 Team,18,4.0,2026-03-07 05:48:27.021000+00:00,3668.309,3770.445,...,213.0,NaN,252.0,False,1.0,None,True,None,False,False

In [10]:
data_telemetry = pd.read_parquet('../data/gold/telemetry_car_Y2026R01.parquet')
aux = data_laps.sort_values(by=['time_lap']).iloc[:1]
join_on = ['session_id', 'driver_number', 'lap_number']

In [11]:
fig = plot_module.plot_synced_timeseries(
    df=data_telemetry.merge(aux[join_on], on=join_on, how='inner').assign(brake=lambda df: df['brake']*100),
    x_col='timing_from_lap',
    title='Telemetry Analysis: 2026',
    subplot_configs=[
        {
            'title': 'Speed',
            'y_label': 'Speed (km/h)',
            'traces': [
                {'y': 'speed', 'name': 'Speed (km/h)', 'line': {'color': 'blue'}},
            ]
        },
        {
            'title': 'Gear',
            'y_label': 'Gear',
            'traces': [
                {'y': 'ngear', 'name': 'Gear selection', 'line': {'color': 'blue'}},
            ]
        },
        {
            'title': 'Throttle and Brake',
            'y_label': 'Pedal position',
            'traces': [
                {'y': 'throttle', 'name': 'Throttle', 'line': {'color': 'blue'}},
                {'y': 'brake', 'name': 'Brake', 'line': {'color': 'red'}},
            ]
        },
    ]
)

In [12]:
fig.show()

## Adding distance

In [15]:
from scipy.spatial import KDTree
data_telemetry

,year,session_id,driver_number,lap_number,timestamp,timing_from_session,timing_from_lap,track_status,rpm,speed,ngear,throttle,brake,drs
0,2026,Y2026R01S1,1,1,2026-03-06 01:31:54.367000+00:00,1014.355,0.279,1,3596.0,14.0,1.0,0.0,0.0,0.0
1,2026,Y2026R01S1,1,1,2026-03-06 01:31:54.607000+00:00,1014.595,0.519,1,3316.0,19.0,1.0,0.0,0.0,0.0
2,2026,Y2026R01S1,1,1,2026-03-06 01:31:55.007000+00:00,1014.995,0.919,1,4469.0,19.0,1.0,0.0,0.0,0.0
3,2026,Y2026R01S1,1,1,2026-03-06 01:31:55.407000+00:00,1015.395,1.319,1,3305.0,23.0,1.0,0.0,0.0,0.0
4,2026,Y2026R01S1,1,1,2026-03-06 01:31:55.567000+00:00,1015.555,1.479,1,2954.0,25.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040007,2026,Y2026R01S4,87,18,2026-03-07 05:50:08.069000+00:00,3769.357,101.048,1,8932.0,72.0,1.0,0.0,1.0,0.0
1040008,2026,Y2026R01S4,87,18,2026-03-07 05:50:08.429000+00:00,3769.717,101.408,1,8412.0,68.0,1.0,0.0,0.0,0.0
1040009,2026,Y2026R01S4,87,18,2026-03-07 05:50:08.629000+00:00,3769.917,101.608,1,8272.0,67.0,1.0,0.0,0.0,0.0
1040010,2026,Y2026R01S4,87,18,2026-03-07 05:50:08.789000+00:00,3770.077,101.768,1,8167.0,67.0,1.0,0.0,0.0,0.0
1040011,2026,Y2026R01S4,87,18,2026-03-07 05:50:09.029000+00:00,3770.317,102.008,1,7983.0,65.0,1.0,0.0,0.0,0.0

In [18]:
data_position = pd.read_parquet('../data/gold/telemetry_pos_Y2026R01.parquet')
data_map = pd.read_parquet('../data/circuit_map_Y2026R01S1_Y2026R01S2_Y2026R01S3_Y2026R01S4.parquet')

In [25]:
tree_columns = ['coordinate_x', 'coordinate_y']
tree = KDTree(data_map[tree_columns])
aux = tree.query(data_position[tree_columns])

In [21]:
data_map

,encoding,coordinate_x,coordinate_y,coordinate_z,derivative_x,derivative_y,derivative_z,total_distance_m,distance_m
0,0.00000,-1216.512055,-1312.483409,84.316142,-38040.657499,35931.207392,-307.518335,5232.657463,0.000000
1,0.00001,-1216.892467,-1312.124104,84.313064,-38041.609030,35929.797830,-308.117848,5232.657463,0.052327
2,0.00002,-1217.272888,-1311.764813,84.309980,-38042.556733,35928.392714,-308.715814,5232.657463,0.104654
3,0.00003,-1217.653318,-1311.405536,84.306889,-38043.500578,35926.992094,-309.312219,5232.657463,0.156981
4,0.00004,-1218.033758,-1311.046273,84.303793,-38044.440534,35925.596019,-309.907049,5232.657463,0.209307
...,...,...,...,...,...,...,...,...,...
99995,0.99995,-1214.610142,-1314.280147,84.331442,-38035.843534,35938.320122,-304.498088,5232.657463,5232.395823
99996,0.99996,-1214.990506,-1313.920771,84.328394,-38036.813731,35936.889088,-305.105113,5232.657463,5232.448152
99997,0.99997,-1215.370879,-1313.561409,84.325340,-38037.780258,35935.462247,-305.710665,5232.657463,5232.500480
99998,0.99998,-1215.751261,-1313.202062,84.322280,-38038.743082,35934.039651,-306.314729,5232.657463,5232.552808
99999,0.99999,-1216.131654,-1312.842728,84.319214,-38039.702173,35932.621349,-306.917291,5232.657463,5232.605136

In [26]:
for col in ['total_distance_m', 'distance_m', 'coordinate_x', 'coordinate_y', 'coordinate_z']:
    data_position[col + "_circuit"] = data_map.iloc[aux[1]][col].values

,year,session_id,driver_number,lap_number,timestamp,timing_from_session,timing_from_lap,track_status,coordinate_x,coordinate_y,coordinate_z,position_status,total_distance_m_circuit,distance_m_circuit,coordinate_x_circuit,coordinate_y_circuit,coordinate_z_circuit
0,2026,Y2026R01S1,1,1,2026-03-06 01:31:54.098000+00:00,1014.086,0.010,1,-1262.0,-1068.0,0.0,OnTrack,5232.657463,20.135738,-1363.147507,-1174.487808,82.918864
1,2026,Y2026R01S1,1,1,2026-03-06 01:31:54.348000+00:00,1014.336,0.260,1,-1271.0,-1059.0,0.0,OnTrack,5232.657463,21.391218,-1372.261623,-1165.853242,82.835991
2,2026,Y2026R01S1,1,1,2026-03-06 01:31:54.688000+00:00,1014.676,0.600,1,-1279.0,-1051.0,0.0,OnTrack,5232.657463,22.542188,-1380.610408,-1157.930416,82.762166
3,2026,Y2026R01S1,1,1,2026-03-06 01:31:54.937000+00:00,1014.925,0.849,1,-1288.0,-1042.0,0.0,OnTrack,5232.657463,23.850249,-1390.090781,-1148.917946,82.680933
4,2026,Y2026R01S1,1,1,2026-03-06 01:31:55.207000+00:00,1015.195,1.119,1,-1305.0,-1026.0,0.0,OnTrack,5232.657463,26.205134,-1407.137113,-1132.670767,82.542246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048245,2026,Y2026R01S4,87,18,2026-03-07 05:50:07.454000+00:00,3768.742,100.433,1,1052.0,-3302.0,82.0,OnTrack,5232.657463,4931.309784,947.799848,-3409.197873,85.811791
1048246,2026,Y2026R01S4,87,18,2026-03-07 05:50:07.714000+00:00,3769.002,100.693,1,1010.0,-3261.0,82.0,OnTrack,5232.657463,4937.206068,905.514640,-3368.105602,85.909518
1048247,2026,Y2026R01S4,87,18,2026-03-07 05:50:08.814000+00:00,3770.102,101.793,1,854.0,-3111.0,82.0,OnTrack,5232.657463,4958.961848,750.708644,-3215.245884,86.730641
1048248,2026,Y2026R01S4,87,18,2026-03-07 05:50:08.914000+00:00,3770.202,101.893,1,767.0,-3026.0,82.0,OnTrack,5232.657463,4971.027430,664.742613,-3130.584283,87.107329
1048249,2026,Y2026R01S4,87,18,2026-03-07 05:50:09.154000+00:00,3770.442,102.133,1,735.0,-2996.0,82.0,OnTrack,5232.657463,4975.374392,633.586331,-3100.271046,87.191305

In [36]:
data_position.merge(
    data_laps.sort_values(by=['time_lap']).iloc[:1][join_on],
    on=join_on, how='inner'
).assign(
    encoding=lambda df: (1.0 * df['distance_m_circuit'] / df['total_distance_m_circuit'])
).assign(
    _cos=lambda df: np.cos(2 * np.pi * df['encoding']),
    _sin=lambda df: np.sin(2 * np.pi * df['encoding']),
)[['timing_from_lap', 'distance_m_circuit', 'encoding', '_cos', '_sin']].sort_values(by=['timing_from_lap'])

     timing_from_lap  distance_m_circuit  encoding      _cos      _sin
0              0.105            3.819188  0.000730  0.999989  0.004586
1              0.465           32.277484  0.006168  0.999249  0.038748
2              0.625           51.489439  0.009840  0.998089  0.061787
3              1.005           75.605681  0.014449  0.995882  0.090660
4              1.266           96.647510  0.018470  0.993274  0.115791
..               ...                 ...       ...       ...       ...
288           77.605         5173.262718  0.988649  0.997458 -0.071259
289           78.005         5193.615055  0.992539  0.998901 -0.046864
290           78.205         5210.142029  0.995697  0.999635 -0.027032
291           78.265         5215.116238  0.996648  0.999778 -0.021061
292           78.505            2.249823  0.000430  0.999996  0.002702

[293 rows x 5 columns]

In [42]:
lap_telemetry = data_telemetry.merge(
    data_laps.sort_values(by=['time_lap']).iloc[:1][join_on],
    on=join_on, how='inner'
)
lap_position = data_position.merge(
    data_laps.sort_values(by=['time_lap']).iloc[:1][join_on],
    on=join_on, how='inner'
)

In [43]:
lap_telemetry

,year,session_id,driver_number,lap_number,timestamp,timing_from_session,timing_from_lap,track_status,rpm,speed,ngear,throttle,brake,drs
0,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.074000+00:00,5424.362,0.045,1,10873.0,279.0,7.0,100.0,0.0,0.0
1,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.514000+00:00,5424.802,0.485,1,11142.0,289.0,7.0,100.0,0.0,0.0
2,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.714000+00:00,5425.002,0.685,1,11169.0,289.0,7.0,100.0,0.0,0.0
3,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.954000+00:00,5425.242,0.925,1,11169.0,291.0,7.0,100.0,0.0,0.0
4,2026,Y2026R01S4,63,21,2026-03-07 06:17:44.154000+00:00,5425.442,1.125,1,11228.0,291.0,7.0,100.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.155000+00:00,5501.443,77.126,1,11341.0,294.0,7.0,100.0,0.0,0.0
275,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.395000+00:00,5501.683,77.366,1,11380.0,294.0,7.0,100.0,0.0,0.0
276,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.675000+00:00,5501.963,77.646,1,11388.0,296.0,7.0,100.0,0.0,0.0
277,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.875000+00:00,5502.163,77.846,1,11410.0,296.0,7.0,100.0,0.0,0.0
278,2026,Y2026R01S4,63,21,2026-03-07 06:19:01.075000+00:00,5502.363,78.046,1,11410.0,297.0,7.0,100.0,0.0,0.0

In [41]:
lap_position

,year,session_id,driver_number,lap_number,timestamp,timing_from_session,timing_from_lap,track_status,coordinate_x,coordinate_y,coordinate_z,position_status,total_distance_m_circuit,distance_m_circuit,coordinate_x_circuit,coordinate_y_circuit,coordinate_z_circuit
0,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.134000+00:00,5424.422,0.105,1,-1245.0,-1287.0,85.0,OnTrack,5232.657463,3.819188,-1244.304333,-1286.287831,84.076815
1,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.494000+00:00,5424.782,0.465,1,-1451.0,-1091.0,83.0,OnTrack,5232.657463,32.277484,-1450.982390,-1090.659672,82.230023
2,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.654000+00:00,5424.942,0.625,1,-1590.0,-958.0,82.0,OnTrack,5232.657463,51.489439,-1589.585962,-957.622629,81.468107
3,2026,Y2026R01S4,63,21,2026-03-07 06:17:44.034000+00:00,5425.322,1.005,1,-1765.0,-792.0,80.0,OnTrack,5232.657463,75.605681,-1764.991545,-792.117199,80.161386
4,2026,Y2026R01S4,63,21,2026-03-07 06:17:44.295000+00:00,5425.583,1.266,1,-1917.0,-647.0,79.0,OnTrack,5232.657463,96.647510,-1917.257956,-646.891136,78.848448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.634000+00:00,5501.922,77.605,1,-786.0,-1722.0,88.0,OnTrack,5232.657463,5173.262718,-786.158765,-1721.828585,86.915104
289,2026,Y2026R01S4,63,21,2026-03-07 06:19:01.034000+00:00,5502.322,78.005,1,-934.0,-1582.0,86.0,OnTrack,5232.657463,5193.615055,-934.269516,-1582.240143,85.646254
290,2026,Y2026R01S4,63,21,2026-03-07 06:19:01.234000+00:00,5502.522,78.205,1,-1054.0,-1468.0,85.0,OnTrack,5232.657463,5210.142029,-1053.833826,-1468.142585,85.107215
291,2026,Y2026R01S4,63,21,2026-03-07 06:19:01.294000+00:00,5502.582,78.265,1,-1090.0,-1434.0,85.0,OnTrack,5232.657463,5215.116238,-1089.666204,-1433.641628,84.998068
292,2026,Y2026R01S4,63,21,2026-03-07 06:19:01.534000+00:00,5502.822,78.505,1,-1233.0,-1297.0,85.0,OnTrack,5232.657463,2.249823,-1232.877807,-1297.045390,84.178583

In [50]:
_distance = np.interp(
    lap_telemetry['timing_from_lap'],
    lap_position['timing_from_lap'],
    lap_position['distance_m_circuit']
)
total = lap_position['total_distance_m_circuit'].iloc[0]
lap_telemetry['enc_cos'] = np.cos(2 * np.pi * _distance / total)
lap_telemetry['enc_sin'] = np.sin(2 * np.pi * _distance / total)
lap_position['enc_cos'] = np.cos(2 * np.pi * lap_position['distance_m_circuit'] / total)
lap_position['enc_sin'] = np.sin(2 * np.pi * lap_position['distance_m_circuit'] / total)

,year,session_id,driver_number,lap_number,timestamp,timing_from_session,timing_from_lap,track_status,rpm,speed,ngear,throttle,brake,drs,enc_cos,enc_sin
0,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.074000+00:00,5424.362,0.045,1,10873.0,279.0,7.0,100.0,0.0,0.0,0.999989,0.004586
1,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.514000+00:00,5424.802,0.485,1,11142.0,289.0,7.0,100.0,0.0,0.0,0.999133,0.041629
2,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.714000+00:00,5425.002,0.685,1,11169.0,289.0,7.0,100.0,0.0,0.0,0.997796,0.066350
3,2026,Y2026R01S4,63,21,2026-03-07 06:17:43.954000+00:00,5425.242,0.925,1,11169.0,291.0,7.0,100.0,0.0,0.0,0.996416,0.084587
4,2026,Y2026R01S4,63,21,2026-03-07 06:17:44.154000+00:00,5425.442,1.125,1,11228.0,291.0,7.0,100.0,0.0,0.0,0.994762,0.102222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.155000+00:00,5501.443,77.126,1,11341.0,294.0,7.0,100.0,0.0,0.0,0.991017,-0.133735
275,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.395000+00:00,5501.683,77.366,1,11380.0,294.0,7.0,100.0,0.0,0.0,0.994037,-0.109039
276,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.675000+00:00,5501.963,77.646,1,11388.0,296.0,7.0,100.0,0.0,0.0,0.997633,-0.068760
277,2026,Y2026R01S4,63,21,2026-03-07 06:19:00.875000+00:00,5502.163,77.846,1,11410.0,296.0,7.0,100.0,0.0,0.0,0.998399,-0.056565
278,2026,Y2026R01S4,63,21,2026-03-07 06:19:01.075000+00:00,5502.363,78.046,1,11410.0,297.0,7.0,100.0,0.0,0.0,0.999084,-0.042799