In [1]:
import pandas as pd

In [2]:
session_ids = ['Y2025R01S1', 'Y2025R01S2', 'Y2025R01S3', 'Y2025R01S4', 'Y2025R01S5']

In [3]:
data_laps = pd.read_parquet('../data/gold/session_laps_Y2025.parquet')
data_laps = data_laps[data_laps['session_id'].isin(session_ids)]
data_laps['session_id'].value_counts().sort_index()

session_id
Y2025R01S1    421
Y2025R01S2    552
Y2025R01S3    352
Y2025R01S4    297
Y2025R01S5    927
Name: count, dtype: int64

In [4]:
data_laps[['driver_name', 'timestamp_lap_start', 'time_lap', 'is_accurate']].sort_values(by=['timestamp_lap_start'])

     driver_name              timestamp_lap_start  time_lap  is_accurate
262          HUL 2025-03-14 01:30:03.090000+00:00       NaN        False
64           HAD 2025-03-14 01:30:14.414000+00:00   114.270        False
21           NOR 2025-03-14 01:30:15.751000+00:00       NaN        False
42           BOR 2025-03-14 01:30:19.108000+00:00   122.622        False
109          GAS 2025-03-14 01:30:28.190000+00:00   109.445        False
...          ...                              ...       ...          ...
2319         OCO 2025-03-16 05:59:31.754000+00:00    90.924         True
2548         BEA 2025-03-16 05:59:39.316000+00:00    90.553         True
1781         BOR                              NaT       NaN        False
1930         ALO                              NaT       NaN        False
2262         LAW                              NaT       NaN        False

[2549 rows x 4 columns]

In [5]:
data_laps[['is_fastf1_generated', 'is_accurate']].value_counts()

is_fastf1_generated  is_accurate
False                True           1456
                     False          1087
True                 False             6
Name: count, dtype: int64

In [6]:
data_laps.query('is_accurate')\
    [['driver_name', 'timestamp_lap_start', 'time_lap', 'is_accurate']].sort_values(by=['timestamp_lap_start'])

     driver_name              timestamp_lap_start  time_lap  is_accurate
22           NOR 2025-03-14 01:32:00.777000+00:00    81.896         True
65           HAD 2025-03-14 01:32:06.688000+00:00    86.964         True
110          GAS 2025-03-14 01:32:13.641000+00:00    81.074         True
43           BOR 2025-03-14 01:32:19.658000+00:00    85.186         True
90           DOO 2025-03-14 01:32:26.714000+00:00    81.807         True
...          ...                              ...       ...          ...
2491         PIA 2025-03-16 05:59:20.420000+00:00    89.517         True
1840         GAS 2025-03-16 05:59:24.705000+00:00    91.312         True
2101         TSU 2025-03-16 05:59:27.924000+00:00    91.511         True
2319         OCO 2025-03-16 05:59:31.754000+00:00    90.924         True
2548         BEA 2025-03-16 05:59:39.316000+00:00    90.553         True

[1456 rows x 4 columns]

In [7]:
import sys
sys.path.append('..')
import src.visualization_app.plotly_time_sync as plot_module

In [8]:
data_laps.sort_values(by=['time_lap'])

,year,session_id,driver_number,driver_name,driver_team,lap_number,stint,timestamp_lap_start,timing_start_lap,timing_end_lap,...,speed_i2,speed_fl,speed_st,is_personal_best,track_status,position,deleted_status,deleted_reason,is_accurate,is_fastf1_generated
1360,2025,Y2025R01S4,4,NOR,McLaren,19,7,2025-03-15 05:58:00.239000+00:00,4228.640,4303.736,...,325.0,310.0,326.0,True,1,NaN,True,None,True,False
1619,2025,Y2025R01S4,81,PIA,McLaren,17,7,2025-03-15 05:57:49.928000+00:00,4218.329,4293.509,...,325.0,309.0,323.0,True,1,NaN,True,None,True,False
1354,2025,Y2025R01S4,4,NOR,McLaren,13,5,2025-03-15 05:39:39.654000+00:00,3128.055,3203.470,...,325.0,310.0,328.0,True,1,NaN,True,None,True,False
1611,2025,Y2025R01S4,81,PIA,McLaren,9,4,2025-03-15 05:28:14.956000+00:00,2443.357,2518.825,...,324.0,305.0,323.0,True,1,NaN,True,None,True,False
1340,2025,Y2025R01S4,1,VER,Red Bull Racing,16,6,2025-03-15 05:58:21.775000+00:00,4250.176,4325.657,...,330.0,310.0,331.0,True,1,NaN,True,None,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2478,2025,Y2025R01S5,81,PIA,McLaren,44,5,2025-03-16 05:35:28.977000+00:00,8886.358,9077.415,...,290.0,NaN,302.0,False,12,15.0,True,None,False,False
2493,2025,Y2025R01S5,87,BEA,Haas F1 Team,2,1,2025-03-16 04:20:52.532000+00:00,4409.913,4579.855,...,178.0,NaN,142.0,False,4,17.0,True,None,False,False
2494,2025,Y2025R01S5,87,BEA,Haas F1 Team,3,2,2025-03-16 04:23:42.474000+00:00,4579.855,4745.266,...,149.0,NaN,122.0,False,4,17.0,True,None,False,False
2495,2025,Y2025R01S5,87,BEA,Haas F1 Team,4,3,2025-03-16 04:26:27.885000+00:00,4745.266,4910.926,...,100.0,NaN,123.0,False,4,17.0,True,None,False,False
2527,2025,Y2025R01S5,87,BEA,Haas F1 Team,36,4,2025-03-16 05:21:03.202000+00:00,8020.583,8181.206,...,166.0,222.0,157.0,False,4,15.0,True,None,False,False

In [9]:
data_telemetry = pd.read_parquet('../data/gold/telemetry_car_Y2025R01.parquet')
aux = data_laps.sort_values(by=['time_lap']).iloc[:1]
join_on = ['session_id', 'driver_number', 'lap_number']

In [10]:
fig = plot_module.plot_synced_timeseries(
    df=data_telemetry.merge(aux[join_on], on=join_on, how='inner').assign(brake=lambda df: df['brake']*100),
    x_col='timing_from_lap',
    title='Telemetry Analysis: 2025',
    subplot_configs=[
        {
            'title': 'Speed',
            'y_label': 'Speed (km/h)',
            'traces': [
                {'y': 'speed', 'name': 'Speed (km/h)', 'line': {'color': 'blue'}},
            ]
        },
        {
            'title': 'Gear',
            'y_label': 'Gear',
            'traces': [
                {'y': 'ngear', 'name': 'Gear selection', 'line': {'color': 'blue'}},
            ]
        },
        {
            'title': 'Throttle and Brake',
            'y_label': 'Pedal position',
            'traces': [
                {'y': 'throttle', 'name': 'Throttle', 'line': {'color': 'blue'}},
                {'y': 'brake', 'name': 'Brake', 'line': {'color': 'red'}},
            ]
        },
    ]
)

In [11]:
fig.show()