In [65]:
import pathlib
import pandas as pd

In [66]:
files = list(pathlib.Path("data/bronze").resolve().rglob("*"))

In [67]:
def file_properties(fl):
    parts = fl.name.split(".")[-2].split("_")
    df = pd.read_parquet(fl)
    return {
        "session_id": parts[-1],
        "type": "_".join(parts[:-1]),
        "name": fl.name,
        "shape": tuple(df.shape),
    }

In [68]:
file_types = pd.DataFrame([file_properties(x) for x in files])

In [69]:
aux = file_types[file_types["session_id"].apply(len)==10]
df = (
    aux[["session_id"]].drop_duplicates().assign(k=1)
    .merge(aux[["type"]].drop_duplicates().assign(k=1), on=["k"])
    .merge(aux.assign(exists=lambda df: df['shape'].apply(lambda x: x[0]>0)), on=["session_id", "type"], how="left")
    .fillna({"exists": False})
)
# df = df[(df["session_id"].apply(len)==10) & (df["type"] != "schedule")]

In [70]:
df["exists"].value_counts()

exists
True    1215
Name: count, dtype: int64

In [71]:
df[~df["exists"]]

Empty DataFrame
Columns: [session_id, k, type, name, shape, exists]
Index: []

In [72]:
df["session_id"].apply(len).value_counts()

session_id
10    1215
Name: count, dtype: int64

In [73]:
df[(df["session_id"].apply(len)==5) & df['exists']]

Empty DataFrame
Columns: [session_id, k, type, name, shape, exists]
Index: []

In [74]:
df['type'].value_counts()

type
circuit                          135
session_laps                     135
session_metadata                 135
session_race_control_messages    135
session_results                  135
session_track_status             135
session_weather                  135
telemetry_car                    135
telemetry_pos                    135
Name: count, dtype: int64

In [75]:
df[df['type']=='circuit']['shape'].apply(lambda x: x[0]).describe()

count    135.000000
mean      54.481481
std        6.303105
min       42.000000
25%       51.000000
50%       56.000000
75%       59.000000
max       69.000000
Name: shape, dtype: float64

In [76]:
df.assign(n_points=lambda df: df['shape'].apply(lambda x: x[0])).groupby(['type']).describe()['n_points']

,count,mean,std,min,25%,50%,75%,max
type,,,,,,,,
circuit,135.0,54.481481,6.303105,42.0,51.0,56.0,59.0,69.0
session_laps,135.0,546.733333,305.801448,185.0,324.5,440.0,593.5,1425.0
session_metadata,135.0,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0
session_race_control_messages,135.0,51.481481,40.999791,3.0,19.5,43.0,71.0,202.0
session_results,135.0,20.214815,0.639323,19.0,20.0,20.0,20.0,22.0
session_track_status,135.0,11.155556,10.164958,1.0,5.0,9.0,14.0,59.0
session_weather,135.0,99.696296,39.655470,10.0,79.5,82.0,107.0,246.0
telemetry_car,135.0,263239.837037,74241.610691,119837.0,210453.5,262426.0,289286.5,453075.0
telemetry_pos,135.0,269109.881481,75921.111097,123127.0,214949.5,267658.0,294282.0,463516.0

In [77]:
df.assign(n_points=lambda df: df['shape'].apply(lambda x: x[1])).groupby(['type']).describe()['n_points']

                               count  mean  std   min   25%   50%   75%   max
type
circuit                        135.0  10.0  0.0  10.0  10.0  10.0  10.0  10.0
session_laps                   135.0  33.0  0.0  33.0  33.0  33.0  33.0  33.0
session_metadata               135.0  11.0  0.0  11.0  11.0  11.0  11.0  11.0
session_race_control_messages  135.0  11.0  0.0  11.0  11.0  11.0  11.0  11.0
session_results                135.0  24.0  0.0  24.0  24.0  24.0  24.0  24.0
session_track_status           135.0   5.0  0.0   5.0   5.0   5.0   5.0   5.0
session_weather                135.0  10.0  0.0  10.0  10.0  10.0  10.0  10.0
telemetry_car                  135.0  20.0  0.0  20.0  20.0  20.0  20.0  20.0
telemetry_pos                  135.0  18.0  0.0  18.0  18.0  18.0  18.0  18.0

In [78]:
df['session_id'].apply(lambda x: x[:-2]).value_counts()

session_id
Y2025R01    45
Y2025R02    45
Y2025R03    45
Y2025R04    45
Y2025R05    45
Y2025R06    45
Y2025R07    45
Y2025R08    45
Y2025R09    45
Y2025R10    45
Y2025R11    45
Y2025R12    45
Y2025R13    45
Y2025R14    45
Y2025R15    45
Y2025R16    45
Y2025R17    45
Y2025R18    45
Y2025R19    45
Y2025R20    45
Y2025R21    45
Y2025R22    45
Y2025R23    45
Y2025R24    45
Y2026R01    45
Y2026R02    45
Y2026R03    45
Name: count, dtype: int64

In [ ]:
reindall