In [3]:
import pandas as pd
import fastf1

In [2]:
schedule = fastf1.get_event_schedule(year=2026, include_testing=True)

req         WARNING 	DEFAULT CACHE ENABLED! (355.1 MB) /Users/tiagobbatalhao/Library/Caches/fastf1

In [3]:
session = fastf1.get_testing_session(2026, 1, 1)
session.load(weather=True, laps=True, messages=True)

core           INFO 	Loading data for Pre-Season Testing - Practice 1 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...

_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Driver  3: Encountered 1 timing integrity error(s) near lap(s): [8].
This might be a bug and should be reported.
_api        WARNING 	Driver 44: Encountered 1 timing integrity error(s) near lap(s): [6].
This might be a bug and should be reported.
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 6
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
core        WARNING 	No lap data for driver 14
core        WARNING 	No lap data for driver 30
core        WARNING 	No lap data for driver 87
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 6)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 14)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 30)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 87)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

In [4]:
vars(session)

{'event': RoundNumber                                                   0
 Country                                                 Bahrain
 Location                                                Bahrain
 OfficialEventName    FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026
 EventDate                                   2026-02-13 00:00:00
 EventName                                    Pre-Season Testing
 EventFormat                                             testing
 Session1                                             Practice 1
 Session1Date                          2026-02-11 10:00:00+03:00
 Session1DateUtc                             2026-02-11 07:00:00
 Session2                                             Practice 2
 Session2Date                          2026-02-12 10:00:00+03:00
 Session2DateUtc                             2026-02-12 07:00:00
 Session3                                             Practice 3
 Session3Date                          2026-02-13 10:00:00+03:00
 Session3DateUtc                             2026-02-13 07:00:00
 Session4                                                   None
 Session4Date                                                NaT
 Session4DateUtc                                             NaT
 Session5                                                   None
 Session5Date                                                NaT
 Session5DateUtc                                             NaT
 F1ApiSupport                                               True
 Name: 0, dtype: object,
 'name': 'Practice 1',
 'f1_api_support': np.True_,
 'date': Timestamp('2026-02-11 07:00:00'),
 'api_path': '/static/2026/2026-02-13_Pre-Season_Testing/2026-02-11_Day_1/',
 '_RACE_LIKE_SESSIONS': ('Race', 'Sprint'),
 '_QUALI_LIKE_SESSIONS': ('Qualifying', 'Sprint Qualifying'),
 '_ergast': <fastf1.ergast.interface.Ergast at 0x11170bb60>,
 '_session_split_times': [datetime.timedelta(0),
  datetime.timedelta(days=1),
  datetime.timedelta(days=1)],
 '_session_info': {'Meeting': {'Key': 1304,
   'Name': 'Pre-Season Testing',
   'OfficialName': 'FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026',
   'Location': 'Bahrain',
   'Number': 1,
   'Country': {'Key': 36, 'Code': 'BRN', 'Name': 'Bahrain'},
   'Circuit': {'Key': 63, 'ShortName': 'Sakhir'}},
  'SessionStatus': 'Inactive',
  'ArchiveStatus': {'Status': 'Generating'},
  'Key': 11465,
  'Type': 'Practice',
  'Number': 1,
  'Name': 'Day 1',
  'StartDate': datetime.datetime(2026, 2, 11, 10, 0),
  'EndDate': datetime.datetime(2026, 2, 11, 19, 0),
  'GmtOffset': datetime.timedelta(seconds=10800),
  'Path': '2026/2026-02-13_Pre-Season_Testing/2026-02-11_Day_1/'},
 '_results':    DriverNumber BroadcastName Abbreviation DriverId         TeamName  \
 1             1      L NORRIS          NOR                   McLaren
 3             3  M VERSTAPPEN          VER           Red Bull Racing
 5             5   G BORTOLETO          BOR                      Audi
 6             6      I HADJAR          HAD           Red Bull Racing
 10           10       P GASLY          GAS                    Alpine
 11           11       S PEREZ          PER                  Cadillac
 12           12   K ANTONELLI          ANT                  Mercedes
 14           14      F ALONSO          ALO              Aston Martin
 16           16     C LECLERC          LEC                   Ferrari
 18           18      L STROLL          STR              Aston Martin
 23           23       A ALBON          ALB                  Williams
 27           27  N HULKENBERG          HUL                      Audi
 30           30      L LAWSON          LAW              Racing Bulls
 31           31        E OCON          OCO              Haas F1 Team
 41           41    A LINDBLAD          LIN              Racing Bulls
 43           43   F COLAPINTO          COL                    Alpine
 44           44    L HAMILTON          HAM                   Ferrari
 55           55       C SAINZ          SAI                  Williams
 63           63     G RUSSELL          RUS                  Mercedes
 77           77      V BOTTAS          BOT                  Cadillac
 81           81     O PIASTRI          PIA                   McLaren
 87           87     O BEARMAN          BEA              Haas F1 Team

    TeamColor TeamId  FirstName    LastName           FullName  ... Position  \
 1     F47600             Lando      Norris       Lando Norris  ...      NaN
 3     4781D7               Max  Verstappen     Max Verstappen  ...      NaN
 5     F50537           Gabriel   Bortoleto  Gabriel Bortoleto  ...      NaN
 6     4781D7             Isack      Hadjar       Isack Hadjar  ...      NaN
 10    00A1E8            Pierre       Gasly       Pierre Gasly  ...      NaN
 11    909090            Sergio       Perez       Sergio Perez  ...      NaN
 12    00D7B6              Kimi   Antonelli     Kimi Antonelli  ...      NaN
 14    229971          Fernando      Alonso    Fernando Alonso  ...      NaN
 16    ED1131           Charles     Leclerc    Charles Leclerc  ...      NaN
 18    229971             Lance      Stroll       Lance Stroll  ...      NaN
 23    1868DB         Alexander       Albon    Alexander Albon  ...      NaN
 27    F50537              Nico  Hulkenberg    Nico Hulkenberg  ...      NaN
 30    6C98FF              Liam      Lawson        Liam Lawson  ...      NaN
 31    9C9FA2           Esteban        Ocon       Esteban Ocon  ...      NaN
 41    6C98FF             Arvid    Lindblad     Arvid Lindblad  ...      NaN
 43    00A1E8            Franco   Colapinto   Franco Colapinto  ...      NaN
 44    ED1131             Lewis    Hamilton     Lewis Hamilton  ...      NaN
 55    1868DB            Carlos       Sainz       Carlos Sainz  ...      NaN
 63    00D7B6            George     Russell     George Russell  ...      NaN
 77    909090          Valtteri      Bottas    Valtteri Bottas  ...      NaN
 81    F47600             Oscar     Piastri      Oscar Piastri  ...      NaN
 87    9C9FA2            Oliver     Bearman     Oliver Bearman  ...      NaN

    ClassifiedPosition  GridPosition  Q1  Q2  Q3 Time Status Points Laps
 1                               NaN NaT NaT NaT  NaT           NaN  NaN
 3                               NaN NaT NaT NaT  NaT           NaN  NaN
 5                               NaN NaT NaT NaT  NaT           NaN  NaN
 6                               NaN NaT NaT NaT  NaT           NaN  NaN
 10                              NaN NaT NaT NaT  NaT           NaN  NaN
 11                              NaN NaT NaT NaT  NaT           NaN  NaN
 12                              NaN NaT NaT NaT  NaT           NaN  NaN
 14                              NaN NaT NaT NaT  NaT           NaN  NaN
 16                              NaN NaT NaT NaT  NaT           NaN  NaN
 18                              NaN NaT NaT NaT  NaT           NaN  NaN
 23                              NaN NaT NaT NaT  NaT           NaN  NaN
 27                              NaN NaT NaT NaT  NaT           NaN  NaN
 30                              NaN NaT NaT NaT  NaT           NaN  NaN
 31                              NaN NaT NaT NaT  NaT           NaN  NaN
 41                              NaN NaT NaT NaT  NaT           NaN  NaN
 43                              NaN NaT NaT NaT  NaT           NaN  NaN
 44                              NaN NaT NaT NaT  NaT           NaN  NaN
 55                              NaN NaT NaT NaT  NaT           NaN  NaN
 63                              NaN NaT NaT NaT  NaT           NaN  NaN
 77                              NaN NaT NaT NaT  NaT           NaN  NaN
 81                              NaN NaT NaT NaT  NaT           NaN  NaN
 87                              NaN NaT NaT NaT  NaT           NaN  NaN

 [22 rows x 22 columns],
 '_session_start_time': datetime.timedelta(seconds=636, microseconds=225000),
 '_session_status':                      Time     Status
 0  0 days 00:00:10.398000   Inactive
 1  0 days 00:10:36.225000    Started
 2  0 days 01:47:52.002000    Aborted
 3  0 days 01:52:57.129000   Inactive
 4  0 days 01:53:34.502000    Started
 5  0 days 04:10:34.479000   Finished
 6  0 days 05:07:40.306000   Inactive
 7  0 days 05:10:34.449000    Started
 8  0 days 06:42:17.837000    Aborted
 9  0 days 06:45:02.177000   Inactive
 10 0 days 06:45:34.485000    Started
 11 0 days 09:10:34.496000   Finished
 12 0 days 09:18:51.009000  Finalised
 13 0 days 09:18:51.009000       Ends,
 '_total_laps': None,
 '_track_status':                      Time Status      Message
 0         0 days 00:00:00      2       Yellow
 1  0 days 00:01:33.692000      1     AllClear
 2  0 days 01:29:47.118000      2       Yellow
 3  0 days 01:29:53.123000      1     AllClear
 4  0 days 01:41:43.302000      2       Yellow
 5  0 days 01:41:52.825000      1     AllClear
 6  0 days 01:46:20.620000      2       Yellow
 7  0 days 01:47:52.347000      5          Red
 8  0 days 01:49:16.377000      1     AllClear
 9  0 days 02:07:42.218000      2       Yellow
 10 0 days 02:07:44.232000      1     AllClear
 11 0 days 02:13:44.930000      2       Yellow
 12 0 days 02:13:48.432000      1     AllClear
 13 0 days 04:13:55.146000      2       Yellow
 14 0 days 04:14:00.645000      1     AllClear
 15 0 days 05:45:51.154000      2       Yellow
 16 0 days 05:45:52.159000      1     AllClear
 17 0 days 06:41:15.272000      2       Yellow
 18 0 days 06:42:18.066000      5          Red
 19 0 days 06:44:55.326000      1     AllClear
 20 0 days 09:15:32.830000      6  VSCDeployed
 21 0 days 09:17:52.807000      7    VSCEnding
 22 0 days 09:18:03.248000      1     AllClear,
 '_laps':                        Time Driver DriverNumber                LapTime  \
 0    0 days 05:32:29.176000    NOR            1                    NaT
 1    0 days 05:34:59.341000    NOR            1                    NaT
 2    0 days 05:54:31.061000    NOR            1                    NaT
 3    0 days 05:57:05.153000    NOR            1                    NaT
 4    0 days 06:11:16.633000    NOR            1                    NaT
 ...                     ...    ...          ...                    ...
 1123 0 days 03:56:47.003000    PIA           81 0 days 00:01:41.173000
 1124 0 days 03:58:28.652000    PIA           81 0 days 00:01:41.649000
 1125 0 days 04:00:10.183000    PIA           81 0 days 00:01:41.531000
 1126 0 days 04:01:51.442000    PIA           81 0 days 00:01:41.259000
 1127 0 days 04:03:36.747000    PIA           81 0 days 00:01:45.305000

       LapNumber  Stint             PitOutTime              PitInTime  \
 0           1.0    1.0 0 days 05:30:31.076000                    NaT
 1           2.0    1.0                    NaT 0 days 05:34:57.162000
 2           3.0    2.0 0 days 05:52:38.791000                    NaT
 3           4.0    2.0                    NaT 0 days 05:57:03.244000
 4           5.0    3.0 0 days 06:09:29.789000                    NaT
 ...         ...    ...                    ...                    ...
 1123       50.0   11.0                    NaT                    NaT
 1124       51.0   11.0                    NaT                    NaT
 1125       52.0   11.0                    NaT                    NaT
 1126       53.0   11.0                    NaT                    NaT
 1127       54.0   11.0                    NaT 0 days 04:03:34.885000

                 Sector1Time            Sector2Time  ... FreshTyre     Team  \
 0                       NaT 0 days 00:00:52.528000  ...      True  McLaren
 1    0 days 00:00:44.845000 0 days 00:01:01.493000  ...      True  McLaren
 2                       NaT 0 days 00:00:48.124000  ...     False  McLaren
 3    0 days 00:00:44.081000 0 days 00:01:06.918000  ...     False  McLaren
 4                       NaT 0 days 00:00:46.551000  ...     False  McLaren
 ...                     ...                    ...  ...       ...      ...
 1123 0 days 00:00:31.924000 0 days 00:00:44.784000  ...     False  McLaren
 1124 0 days 00:00:32.136000 0 days 00:00:44.871000  ...     False  McLaren
 1125 0 days 00:00:31.914000 0 days 00:00:45.036000  ...     False  McLaren
 1126 0 days 00:00:31.752000 0 days 00:00:44.859000  ...     False  McLaren
 1127 0 days 00:00:31.924000 0 days 00:00:45.436000  ...     False  McLaren

                LapStartTime            LapStartDate  TrackStatus  Position  \
 0    0 days 05:30:31.076000 2026-02-11 12:19:56.700            1       NaN
 1    0 days 05:32:29.176000 2026-02-11 12:21:54.800            1       NaN
 2    0 days 05:34:59.341000 2026-02-11 12:24:24.965           12       NaN
 3    0 days 05:54:31.061000 2026-02-11 12:43:56.685            1       NaN
 4    0 days 05:57:05.153000 2026-02-11 12:46:30.777            1       NaN
 ...                     ...                     ...          ...       ...
 1123 0 days 03:55:05.830000 2026-02-11 10:44:31.454            1       NaN
 1124 0 days 03:56:47.003000 2026-02-11 10:46:12.627            1       NaN
 1125 0 days 03:58:28.652000 2026-02-11 10:47:54.276            1       NaN
 1126 0 days 04:00:10.183000 2026-02-11 10:49:35.807            1       NaN
 1127 0 days 04:01:51.442000 2026-02-11 10:51:17.066            1       NaN

       Deleted  DeletedReason  FastF1Generated IsAccurate
 0       False                           False      False
 1       False                           False      False
 2       False                           False      False
 3       False                           False      False
 4       False                           False      False
 ...       ...            ...              ...        ...
 1123    False                           False       True
 1124    False                           False       True
 1125    False                           False       True
 1126    False                           False       True
 1127    False                           False      False

 [1128 rows x 31 columns],
 '_t0_date': Timestamp('2026-02-11 06:49:25.624000'),
 '_car_data': {'1':                           Date  RPM  Speed  nGear  Throttle  Brake  DRS  \
  0      2026-02-11 06:49:28.028  0.0    0.0      0       0.0  False    0
  1      2026-02-11 06:49:28.828  0.0    0.0      0       0.0  False    0
  2      2026-02-11 06:49:29.188  0.0    0.0      0       0.0  False    0
  3      2026-02-11 06:49:29.428  0.0    0.0      0       0.0  False    0
  4      2026-02-11 06:49:29.708  0.0    0.0      0       0.0  False    0
  ...                        ...  ...    ...    ...       ...    ...  ...
  111636 2026-02-11 16:07:26.815  0.0    0.0      0       0.0  False    0
  111637 2026-02-11 16:07:27.055  0.0    0.0      0       0.0  False    0
  111638 2026-02-11 16:07:27.335  0.0    0.0      0       0.0  False    0
  111639 2026-02-11 16:07:27.656  0.0    0.0      0       0.0  False    0
  111640 2026-02-11 16:07:27.816  0.0    0.0      0       0.0  False    0

         Source                   Time            SessionTime
  0         car 0 days 00:00:02.404000 0 days 00:00:02.404000
  1         car 0 days 00:00:03.204000 0 days 00:00:03.204000
  2         car 0 days 00:00:03.564000 0 days 00:00:03.564000
  3         car 0 days 00:00:03.804000 0 days 00:00:03.804000
  4         car 0 days 00:00:04.084000 0 days 00:00:04.084000
  ...       ...                    ...                    ...
  111636    car 0 days 09:18:01.191000 0 days 09:18:01.191000
  111637    car 0 days 09:18:01.431000 0 days 09:18:01.431000
  111638    car 0 days 09:18:01.711000 0 days 09:18:01.711000
  111639    car 0 days 09:18:02.032000 0 days 09:18:02.032000
  111640    car 0 days 09:18:02.192000 0 days 09:18:02.192000

  [111641 rows x 10 columns],
  '3':                           Date  RPM  Speed  nGear  Throttle  Brake  DRS  \
  0      2026-02-11 06:49:28.028  0.0    0.0      0       0.0  False    0
  1      2026-02-11 06:49:28.828  0.0    0.0      0       0.0  False    0
  2      2026-02-11 06:49:29.188  0.0    0.0      0       0.0  False    0
  3      2026-02-11 06:49:29.428  0.0    0.0      0       0.0  False    0
  4      2026-02-11 06:49:29.708  0.0    0.0      0       0.0  False    0
  ...                        ...  ...    ...    ...       ...    ...  ...
  111636 2026-02-11 16:07:26.815  0.0    0.0      0       0.0  False    0
  111637 2026-02-11 16:07:27.055  0.0    0.0      0       0.0  False    0
  111638 2026-02-11 16:07:27.335  0.0    0.0      0       0.0  False    0
  111639 2026-02-11 16:07:27.656  0.0    0.0      0       0.0  False    0
  111640 2026-02-11 16:07:27.816  0.0    0.0      0       0.0  False    0

         Source                   Time            SessionTime
  0         car 0 days 00:00:02.404000 0 days 00:00:02.404000
  1         car 0 days 00:00:03.204000 0 days 00:00:03.204000
  2         car 0 days 00:00:03.564000 0 days 00:00:03.564000
  3         car 0 days 00:00:03.804000 0 days 00:00:03.804000
  4         car 0 days 00:00:04.084000 0 days 00:00:04.084000
  ...       ...                    ...                    ...
  111636    car 0 days 09:18:01.191000 0 days 09:18:01.191000
  111637    car 0 days 09:18:01.431000 0 days 09:18:01.431000
  111638    car 0 days 09:18:01.711000 0 days 09:18:01.711000
  111639    car 0 days 09:18:02.032000 0 days 09:18:02.032000
  111640    car 0 days 09:18:02.192000 0 days 09:18:02.192000

  [111641 rows x 10 columns],
  '5':                           Date  RPM  Speed  nGear  Throttle  Brake  DRS  \
  0      2026-02-11 06:49:28.028  0.0    0.0      0       0.0  False    0
  1      2026-02-11 06:49:28.828  0.0    0.0      0       0.0  False    0
  2      2026-02-11 06:49:29.188  0.0    0.0      0       0.0  False    0
  3      2026-02-11 06:49:29.428  0.0    0.0      0       0.0  False    0
  4      2026-02-11 06:49:29.708  0.0    0.0      0       0.0  False    0
  ...                        ...  ...    ...    ...       ...    ...  ...
  111636 2026-02-11 16:07:26.815  0.0    0.0      0       0.0  False    0
  111637 2026-02-11 16:07:27.055  0.0    0.0      0       0.0  False    0
  111638 2026-02-11 16:07:27.335  0.0    0.0      0       0.0  False    0
  111639 2026-02-11 16:07:27.656  0.0    0.0      0       0.0  False    0
  111640 2026-02-11 16:07:27.816  0.0    0.0      0       0.0  False    0

         Source                   Time            SessionTime
  0         car 0 days 00:00:02.404000 0 days 00:00:02.404000
  1         car 0 days 00:00:03.204000 0 days 00:00:03.204000
  2         car 0 days 00:00:03.564000 0 days 00:00:03.564000
  3         car 0 days 00:00:03.804000 0 days 00:00:03.804000
  4         car 0 days 00:00:04.084000 0 days 00:00:04.084000
  ...       ...                    ...                    ...
  111636    car 0 days 09:18:01.191000 0 days 09:18:01.191000
  111637    car 0 days 09:18:01.431000 0 days 09:18:01.431000
  111638    car 0 days 09:18:01.711000 0 days 09:18:01.711000
  111639    car 0 days 09:18:02.032000 0 days 09:18:02.032000
  111640    car 0 days 09:18:02.192000 0 days 09:18:02.192000

  [111641 rows x 10 columns],
  '6':                           Date  RPM  Speed  nGear  Throttle  Brake  DRS  \
  0      2026-02-11 06:49:28.028  0.0    0.0      0       0.0  False    0
  1      2026-02-11 06:49:28.828  0.0    0.0      0       0.0  False    0
  2      2026-02-11 06:49:29.188  0.0    0.0      0       0.0  False    0
  3      2026-02-11 06:49:29.428  0.0    0.0      0       0.0  False    0
  4      2026-02-11 06:49:29.708  0.0    0.0      0       0.0  False    0
  ...                        ...  ...    ...    ...       ...    ...  ...
  111636 2026-02-11 16:07:26.815  0.0    0.0      0       0.0  False    0
  111637 2026-02-11 16:07:27.055  0.0    0.0      0       0.0  False    0
  111638 2026-02-11 16:07:27.335  0.0    0.0      0       0.0  False    0
  111639 2026-02-11 16:07:27.656  0.0    0.0      0       0.0  False    0
  111640 2026-02-11 16:07:27.816  0.0    0.0      0       0.0  False    0

         Source                   Time            SessionTime
  0         car 0 days 00:00:02.404000 0 days 00:00:02.404000

In [5]:
session.laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 05:32:29.176000,NOR,1,NaT,1.0,1.0,0 days 05:30:31.076000,NaT,NaT,0 days 00:00:52.528000,...,True,McLaren,0 days 05:30:31.076000,2026-02-11 12:19:56.700,1,NaN,False,,False,False
1,0 days 05:34:59.341000,NOR,1,NaT,2.0,1.0,NaT,0 days 05:34:57.162000,0 days 00:00:44.845000,0 days 00:01:01.493000,...,True,McLaren,0 days 05:32:29.176000,2026-02-11 12:21:54.800,1,NaN,False,,False,False
2,0 days 05:54:31.061000,NOR,1,NaT,3.0,2.0,0 days 05:52:38.791000,NaT,NaT,0 days 00:00:48.124000,...,False,McLaren,0 days 05:34:59.341000,2026-02-11 12:24:24.965,12,NaN,False,,False,False
3,0 days 05:57:05.153000,NOR,1,NaT,4.0,2.0,NaT,0 days 05:57:03.244000,0 days 00:00:44.081000,0 days 00:01:06.918000,...,False,McLaren,0 days 05:54:31.061000,2026-02-11 12:43:56.685,1,NaN,False,,False,False
4,0 days 06:11:16.633000,NOR,1,NaT,5.0,3.0,0 days 06:09:29.789000,NaT,NaT,0 days 00:00:46.551000,...,False,McLaren,0 days 05:57:05.153000,2026-02-11 12:46:30.777,1,NaN,False,,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1123,0 days 03:56:47.003000,PIA,81,0 days 00:01:41.173000,50.0,11.0,NaT,NaT,0 days 00:00:31.924000,0 days 00:00:44.784000,...,False,McLaren,0 days 03:55:05.830000,2026-02-11 10:44:31.454,1,NaN,False,,False,True
1124,0 days 03:58:28.652000,PIA,81,0 days 00:01:41.649000,51.0,11.0,NaT,NaT,0 days 00:00:32.136000,0 days 00:00:44.871000,...,False,McLaren,0 days 03:56:47.003000,2026-02-11 10:46:12.627,1,NaN,False,,False,True
1125,0 days 04:00:10.183000,PIA,81,0 days 00:01:41.531000,52.0,11.0,NaT,NaT,0 days 00:00:31.914000,0 days 00:00:45.036000,...,False,McLaren,0 days 03:58:28.652000,2026-02-11 10:47:54.276,1,NaN,False,,False,True
1126,0 days 04:01:51.442000,PIA,81,0 days 00:01:41.259000,53.0,11.0,NaT,NaT,0 days 00:00:31.752000,0 days 00:00:44.859000,...,False,McLaren,0 days 04:00:10.183000,2026-02-11 10:49:35.807,1,NaN,False,,False,True
1127,0 days 04:03:36.747000,PIA,81,0 days 00:01:45.305000,54.0,11.0,NaT,0 days 04:03:34.885000,0 days 00:00:31.924000,0 days 00:00:45.436000,...,False,McLaren,0 days 04:01:51.442000,2026-02-11 10:51:17.066,1,NaN,False,,False,False

In [6]:
session.t0_date

Timestamp('2026-02-11 06:49:25.624000')

In [8]:
import fastf1
fastf1.Cache

FastF1 cache (0B) /Users/tiagobbatalhao/Library/Caches/fastf1

In [41]:
session = fastf1.get_session(2026, 1, 1)
session.load(weather=True, laps=True, messages=True, telemetry=True)

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.6.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 14
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 14)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
logger      WARNING 	Failed to load telemetry data!
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

In [44]:
session.laps.iloc[0].get_car_data()

DataNotLoadedError: The data you are trying to access has not been loaded yet. See `Session.load`

In [32]:
vars(session).keys()

dict_keys(['event', 'name', 'f1_api_support', 'date', 'api_path', '_RACE_LIKE_SESSIONS', '_QUALI_LIKE_SESSIONS', '_ergast', '_session_split_times', '_session_info', '_results', '_session_start_time', '_session_status', '_total_laps', '_track_status', '_laps', '_weather_data', '_race_control_messages'])

In [49]:
fastf1.__version__

'3.6.1'

In [4]:
dfmap = pd.read_parquet('../data/circuit_map_Y2026R01S1_Y2026R01S2_Y2026R01S3_Y2026R01S4.parquet')

In [5]:
dfmap

,encoding,coordinate_x,coordinate_y,coordinate_z,derivative_x,derivative_y,derivative_z,total_distance_m,distance_m
0,0.00000,-1216.512055,-1312.483409,84.316142,-38040.657499,35931.207392,-307.518335,5232.657463,0.000000
1,0.00001,-1216.892467,-1312.124104,84.313064,-38041.609030,35929.797830,-308.117848,5232.657463,0.052327
2,0.00002,-1217.272888,-1311.764813,84.309980,-38042.556733,35928.392714,-308.715814,5232.657463,0.104654
3,0.00003,-1217.653318,-1311.405536,84.306889,-38043.500578,35926.992094,-309.312219,5232.657463,0.156981
4,0.00004,-1218.033758,-1311.046273,84.303793,-38044.440534,35925.596019,-309.907049,5232.657463,0.209307
...,...,...,...,...,...,...,...,...,...
99995,0.99995,-1214.610142,-1314.280147,84.331442,-38035.843534,35938.320122,-304.498088,5232.657463,5232.395823
99996,0.99996,-1214.990506,-1313.920771,84.328394,-38036.813731,35936.889088,-305.105113,5232.657463,5232.448152
99997,0.99997,-1215.370879,-1313.561409,84.325340,-38037.780258,35935.462247,-305.710665,5232.657463,5232.500480
99998,0.99998,-1215.751261,-1313.202062,84.322280,-38038.743082,35934.039651,-306.314729,5232.657463,5232.552808
99999,0.99999,-1216.131654,-1312.842728,84.319214,-38039.702173,35932.621349,-306.917291,5232.657463,5232.605136